AWSTemplateFormatVersion: 2010-09-09
Description: "Osagiede Nosa / This template deploys an EC2 instance in default VPC with a custom security group"

Resources: 
  InstanceSecurityGroup:
    Type: "AWS::EC2::SecurityGroup" 
    Properties: 
      GroupDescription: "Allow http to client host"
      SecurityGroupIngress: 
      - CidrIp: 0.0.0.0/0
        FromPort: 80
        IpProtocol: tcp
        ToPort: 80
      VpcId: vpc-051654bb8298c52be

  Ec2Instance:
    Type: "AWS::EC2::Instance" 
    Properties: 
      ImageId: ami-0022f774911c1d690
      InstanceType: t3.micro
      KeyName: key_1
      NetworkInterfaces: 
      - AssociatePublicIpAddress: "true"
        DeviceIndex: "0"
        GroupSet: 
        - Ref: InstanceSecurityGroup 
        SubnetId: subnet-06998200f5555904c 
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo yum update -y
          sudo yum install -y httpd
          sudo systemctl start httpd
          sudo systemctl enable httpd
      
    

