AWSTemplateFormatVersion: 2010-09-09
Description: "Osagiede Nosa / This template deploys an EC2 instance in default VPC WITH PARAMETERS"

Parameters: 
  ParamVPC:
    Type: "AWS::EC2::VPC::Id"
    Description: "Enter your Vpc"
    Default: vpc-051654bb8298c52be
  ParamSubnet: 
    Type: "AWS::EC2::Subnet::Id"
    Description: "Enter your Subnet"
    Default: subnet-06998200f5555904c
  ParamAMI: 
    Type: "AWS::EC2::Image::Id"
    Description: "Enter your Subnet"
    Default: ami-0022f774911c1d690

Resources: 
  InstanceSecurityGroup:
    Type: "AWS::EC2::SecurityGroup" 
    Properties: 
      GroupDescription: "Allow http to client host"
      SecurityGroupIngress: 
      - CidrIp: 0.0.0.0/0
        FromPort: 80
        IpProtocol: tcp
        ToPort: 80
      VpcId: 
        Ref: ParamVPC

  Ec2Instance:
    Type: "AWS::EC2::Instance" 
    Properties: 
      ImageId: 
        Ref: ParamAMI
      InstanceType: t3.micro
      KeyName: key_1
      NetworkInterfaces: 
      - AssociatePublicIpAddress: "true"
        DeviceIndex: "0"
        GroupSet: 
        - Ref: InstanceSecurityGroup 
        SubnetId: 
          Ref: ParamSubnet 
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo yum update -y
          sudo yum install -y httpd
          sudo systemctl start httpd
          sudo systemctl enable httpd
      
    

