AWSTemplateFormatVersion: 2010-09-09
Description: Osagiede Nosa / This template deploys a VPC
Resources:
    UdacityVPC:
        Type: 'AWS::EC2::VPC'
        Properties:
            Name: 'UDAvp'
            CidrBlock: 10.0.0.0/16
            EnableDnsHostnames: 'true'
            Tags:
              - Key: name
                Value: myfirsttestvpc
